version: 2.1
jobs:
  test-sitespeed:
    machine: true
    steps:
      - run:
          name: Run test - cable
          command: |
            docker run --shm-size=1g --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest -n 1 \
            https://stage.animedigitalnetwork.fr \
            --basicAuth ${BASIC_AUTH} \
            --slack.hookUrl ${SLACK_HOOK_URL} \
            --slack.channel random \
            --browsertime.connectivity.engine tsproxy -c cable \
            --s3.bucketname ${S3_BUCKET} \
            --s3.secret ${S3_SECRET} \
            --s3.key ${S3_KEY} \
            --s3.path cable \
            --outputFolder cable
      # - run:
      #     name: Run test - fast 3g
      #     command: |
      #       docker run --shm-size=1g --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest -n 1 \
      #       https://stage.animedigitalnetwork.fr \
      #       --basicAuth ${BASIC_AUTH} \
      #       --slack.hookUrl ${SLACK_HOOK_URL} \
      #       --browsertime.connectivity.engine tsproxy -c 3gfast \
      #       --s3.bucketname ${S3_BUCKET} \
      #       --s3.secret ${S3_SECRET} \
      #       --s3.key ${S3_KEY} \
      #       --s3.path fast3g \
      #       --outputFolder fast3g
      # - run:
      #     name: Run test - slow 3g
      #     command: |
      #       docker run --shm-size=1g --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest -n 1 \
      #       https://stage.animedigitalnetwork.fr \
      #       --basicAuth ${BASIC_AUTH} \
      #       --slack.hookUrl ${SLACK_HOOK_URL} \
      #       --browsertime.connectivity.engine tsproxy -c 3gslow \
      #       --s3.bucketname ${S3_BUCKET} \
      #       --s3.secret ${S3_SECRET} \
      #       --s3.key ${S3_KEY} \
      #       --s3.path slow3g \
      #       --outputFolder slow3g
      - run:
          name: Compress results
          command: tar -cf ~/project/results.tar ~/project/cable ~/project/fast3g ~/project/slow3g
      - store_artifacts:
          path: ~/project/results.tar

workflows:
  build:
    jobs:
      - test-sitespeed:
          filters:
            branches:
              only: master
