version: 2.1
jobs:
  test-sitespeed:
    machine: true
    steps:
      - run: sudo modprobe ifb numifbs=1
      - run:
          name: Run test
          command: |
             docker run --shm-size=1g --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest https://stage.animedigitalnetwork.fr --basicAuth ${BASIC_AUTH} --slack.hookUrl ${SLACK_HOOK_URL} -n 1
      - store_artifacts:
          path: ~/project/sitespeed-result

workflows:
  build:
    jobs:
      - test-sitespeed
