version: 2.1
jobs:
  test-sitespeed:
    machine: true
    steps:
      - run: sudo modprobe ifb numifbs=1
      - run:
          name: Run test
          command: |
             docker run --shm-size=1g --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest \
             https://stage.animedigitalnetwork.fr \
             https://stage.animedigitalnetwork.fr/video/bleach \
             https://stage.animedigitalnetwork.fr/video/bleach/5534-episode-3-episode-3 \
             -r Authorization:${BASIC_AUTH} \
             --slack.hookUrl ${SLACK_HOOK_URL}
      - store_artifacts:
          path: ~/sitespeed.io

workflows:
  build:
    jobs:
      - test-sitespeed
